name: Sync to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    # Only run in the org repo, skip in personal repo
    if: github.repository == 'cursim-labs/personal-portfolio'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          persist-credentials: true

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push to personal repository
        run: |
          git remote add personal https://${{ secrets.PAT }}@github.com/akashbagchi/akashbagchi.github.io.git
          git push personal main:main --force
