name: Sync to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to personal repository
        env:
          DESTINATION_REPO: "https://oauth2:${{ secrets.PAT }}@github.com/akashbagchi/akashbagchi.github.io.git"
        run: |
          git remote add personal $DESTINATION_REPO
          git push personal main:main --force
