name: Sync to Personal Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Push to personal repository
        env:
          PERSONAL_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Setting up remote..."
          git remote add personal https://${{ secrets.PAT }}@github.com/akashbagchi/akashbagchi.github.io.git
          echo "Pushing to personal repo..."
          git push personal main:main --force
